version: "3"
services:
  data-dog:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV_NAME: production
    restart: always
    depends_on:
      - trading-db
    networks:
      - webservices
    ports:
      - 7001:7001

  trading-db:
    image: bitnami/mysql:latest
    user: root
    container_name: trading-db
    restart: always
    volumes:
      #NOTE: As this is a non-root container, the mounted files and directories must have the proper permissions for the UID 1001.
      - ./trading_db_data:/bitnami/mysql/data
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=nice_trading
      - MYSQL_PASSWORD=Password1
      - MYSQL_DATABASE=my_trading
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=Password1
      - ALLOW_EMPTY_PASSWORD=no
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    networks:
      - webservices

volumes:
  trading_db_data:
    driver: local


networks:
  webservices:
    driver: bridge
