version: "3"
services:
  data-dog:
    build:
      context: ./data-dog
      dockerfile: Dockerfile
    environment:
      ENV_NAME: production
    container_name: data-dog
    restart: always
    depends_on:
      - trading-db
    networks:
      - webservices
    ports:
      - 7001:7001

  trading-db:
    image: bitnami/mysql:latest
    user: root
    container_name: trading-db
    restart: always
    volumes:
      #NOTE: As this is a non-root container, the mounted files and directories must have the proper permissions for the UID 1001.
      - ./database/data/trading_db_data:/bitnami/mysql/data
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=nice_trading
      - MYSQL_PASSWORD=Password1
      - MYSQL_DATABASE=my_trading
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=Password1
      - ALLOW_EMPTY_PASSWORD=no
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    networks:
      - webservices

  bridge-nginx:
    image: nginx:alpine
    container_name: bridge-nginx
    volumes:
      - ./bridge-nginx/conf:/etc/nginx/conf.d
    depends_on:
      - data-dog
    environment:
      - VIRTUAL_HOST=trading.dw3c.com
      #- LETSENCRYPT_HOST=trading.dw3c.com
      #- LETSENCRYPT_EMAIL=lovejunlic@qq.com
    networks:
      - webservices

volumes:
  trading_db_data:
    driver: local
  conf:
    driver: local

networks:
  webservices:
    driver: bridge
