version: "3"
services:
  mysql-auto-backup:
    build:
      context: ./database/backup
      dockerfile: Dockerfile
    volumes: 
      - ./database/backup/mysql_backups:/mysql_backups/:rw 
    environment: 
      - MYSQL_DB_HOST=trading-db
      - MYSQL_DB_USER=root
      - MYSQL_DB_PWD=Password1
      - MYSQL_DB_NAME=my_trading
      - BACKUP_DAYS=3
    depends_on:
      - trading-db
      
  data-dog:
    build:
      context: ./data-dog
      dockerfile: Dockerfile
    environment:
      - ENV_NAME=production
      - VIRTUAL_HOST=trading.dw3c.com
      - VIRTUAL_PORT=7001
    container_name: data-dog
    restart: always
    depends_on:
      - trading-db
    ports:
      - 7001

  trading-db:
    image: bitnami/mysql:latest
    user: root
    container_name: trading-db
    restart: always
    volumes:
      #NOTE: As this is a non-root container, the mounted files and directories must have the proper permissions for the UID 1001.
      - ./database/data/trading_db_data:/bitnami/mysql/data
    ports:
      - 3306
    environment:
      - MYSQL_USER=nice_trading
      - MYSQL_PASSWORD=Password1
      - MYSQL_DATABASE=my_trading
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=Password1
      - ALLOW_EMPTY_PASSWORD=no
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  trading_db_data:
    driver: local
  mysql_backups:
    driver: local
  conf:
    driver: local

networks:
  default:
    external:
      name: webservices
