version: "3"
services:
  mysql-auto-backup:
    build:
      context: ./backup-script
      dockerfile: Dockerfile
    container_name: mysql-auto-backup
    volumes: 
      - ./data/backup:/backup
    environment: 
      DBHOST: trading-db
      USERNAME: root
      PASSWORD: "Password1"
      DBEXCLUDE: "performance_schema information_schema"
      CRON_SCHEDULE: "0 5 * * *"
      EXTRA_OPTS: "--single-transaction"
      DBNAMES: "my_trading"
      DOWEEKLY: 6
    depends_on:
      - trading-db

  trading-db:
    image: bitnami/mysql:latest
    user: root
    container_name: trading-db
    restart: always
    volumes:
      #NOTE: As this is a non-root container, the mounted files and directories must have the proper permissions for the UID 1001.
      - ./data/trading_db_data:/bitnami/mysql/data
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=nice_trading
      - MYSQL_PASSWORD=Password1
      - MYSQL_DATABASE=my_trading
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=Password1
      - ALLOW_EMPTY_PASSWORD=no
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  trading_db_data:
    driver: local
  backup:
    driver: local

networks:
  default:
    external:
      name: webproxy
